### ISSUE TITLE
Inability to get Tooltip Report to appear

### ISSUE THREAD

**Issue by mgwhit216** [liprec/azurebi-docs#136]
We have been using the Hierarchy Slicer in Power BI for the last month or two without issue. Had a tooltip page setup and worked as expected. However, then a few days ago the tooltips just stopped working and can not get them to display anymore. Created a basic report to test and the tooltip report doesn't show on that report either.

Do you have insight in what might have changed in the last week or two that prevents the tooltip from working?

---
#### Document details

⚠ Do not edit this section. It is required for docs.jppp.org ➟ GitHub issue linking.

* document_id=487cd175-be13-40df-a80e-aa1c7f531eb1
* document_url=https://azurebi-docs.jppp.org/powerbi-visuals/hierarchy-slicer.html

**Comment by liprec** [comment]
Hi @mgwhit216,

Thanks for your feedback and indeed since the latest update (v.2.2.1) the tooltips are not triggered correctly anymore.
Good news is that I found the (strange) reason why this was happening an just submitted a new version to be validated.

-JP

**Comment by wwisse** [comment]
Hi JP,

Great news indeed! thanks

Vriendelijke groet,
Wiep

Van: Jan Pieter Posthuma <notifications@github.com>
Verzonden: dinsdag 27 oktober 2020 21:54
Aan: liprec/azurebi-docs <azurebi-docs@noreply.github.com>
CC: Subscribed <subscribed@noreply.github.com>
Onderwerp: Re: [liprec/azurebi-docs] Inability to get Tooltip Report to appear (#136)


Hi @mgwhit216<https://github.com/mgwhit216>,

Thanks for your feedback and indeed since the latest update (v.2.2.1) the tooltips are not triggered correctly anymore.
Good news is that I found the (strange) reason why this was happening an just submitted a new version to be validated.

-JP

**Comment by liprec** [comment]
v2.2.2 is now available which has a fix for this issue.

**Comment by wtg-bko** [comment]
Can we reopen this issue? I am using v2.2.2.0 (last updated 20/09/2025) and for me the tooltip icons do not up on PBI Desktop (even though it's enabled) unless I pick single select with Selection type "Leafs only" but that's not what I need. On powerbi.com sometimes the tooltip icon is visible but other times it's not. I think it has to do with the width/height calculation of the dive element for the item in the list because the icon is actually there if I checked the HTML content. The browser zoom level also affects this somehow as it can visible if I zoomed out the report page to some degree.
