### ISSUE TITLE
Parent item checked automatically if there is just one child

### ISSUE THREAD

**Issue by jiriond** [liprec/azurebi-docs#81]
*Start issue here*
Greetings!
The slicer automatically selects parent item if there is just one child which is selected. Could that be an optional behavior?
it causes problems in some cases, e.g. slicer with Quarters and months which shows only closed and the current month will select the whole quarter Q1 if we are in January and only Jan is displayed in the slicer. That way, the prior year sales will show total sales for 2019 Q1, not only January 2019, making the comparison of current and prior year quite misleading...

if the slicer looks like this, clicking on Jan will select the whole 2020 Q1...
2020 Q1
    Jan
2019 Q4
   Oct
   Nov
   Dec
....

thank you
    Jiri

---
#### Document details

⚠ Do not edit this section. It is required for docs.jppp.org ➟ GitHub issue linking.

* document_id=487cd175-be13-40df-a80e-aa1c7f531eb1
* document_url=https://azurebi-docs.jppp.org/powerbi-visuals/hierarchy-slicer.html

**Comment by liprec** [comment]
Thanks for the feedback and at this moment this is not possible.
In the next release there will be an option to only select the leaves, but that will probably not solve your issue completely as you cannot select 2019 Q4 anymore.

**Comment by jiriond** [comment]
Pity, you are right, the "leaves only" feature won't help us in this case. Is there any chance the functionality will be added in the future? If so, any time estimation? ;)
And many thanks for this great custom visual!

**Comment by Nidomlok** [comment]
I have a similar problem with the slicer selecting the parent instead of the leaf and would like to know if it can be fixed? 
My problem is related to filtering of values in the slicer. When we do a selection in the slicer there is only one leaf visible, because of filtering, even though many leaves are available under the parent. 
When the filter conditions are changed the slicers is going to have the wrong selection since more values are selected than intended.
